export const GET_USER_INFO = 'GET_USER_INFO';
export const SET_USER_INFO = 'GET_USER_INFO';
export const SET_FOOD_ITEMS = 'SET_FOOD_ITEMS';
export const ADD_CART = 'ADD_CART';
export const CLEAR_FOOD_ITEMS = 'CLEAR_FOOD_ITEMS';
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';
export const REMOVE_FOOD_ITEMS = 'REMOVE_FOOD_ITEMS';
